export type Icon =
    'arr-backward' |
    'arr-forward' |
    'arrow-back' |
    'cat-dummy' |
    'check' |
    'chevron-down' |
    'chevron-left' |
    'chevron-right' |
    'chevron-up' |
    'collapse-down' |
    'collapse-left' |
    'collaps-right' |
    'collapse-up' |
    'cross' |
    'delete' |
    'document' |
    'download' |
    'edit' |
    'error' |
    'filter' |
    'folder' |
    'hamburger' |
    'home' |
    'icon-mail' |
    'info' |
    'link-external' |
    'list' |
    'magnifier' |
    'min' |
    'plus' |
    'question' |
    'secure' |
    'success' |
    'upload' |
    'user' |
    'warning--alt' |
    'warning'
